refresh_data:
  name: Refresh Data
  description: Refresh InfoMentor data for all pupils or a specific pupil
  fields:
    pupil_id:
      name: Pupil ID
      description: ID of specific pupil to refresh (optional)
      required: false
      selector:
        text:

switch_pupil:
  name: Switch Pupil
  description: Switch to a different pupil context
  fields:
    pupil_id:
      name: Pupil ID
      description: ID of pupil to switch to
      required: true
      selector:
        text:

force_refresh:
  name: Force Refresh
  description: Force a complete refresh bypassing cache and rate limits
  fields:
    clear_cache:
      name: Clear Cache
      description: Whether to clear cached data
      default: true
      selector:
        boolean:

debug_authentication:
  name: Debug Authentication
  description: Debug the authentication flow and log detailed information

cleanup_duplicate_entities:
  name: Cleanup Duplicate Entities
  description: Remove duplicate InfoMentor entities. Use dry_run first to see what would be removed.
  fields:
    dry_run:
      name: Dry Run
      description: Preview what would be removed without actually removing entities
      default: false
      selector:
        boolean:
    aggressive_cleanup:
      name: Remove All Entities
      description: Remove ALL InfoMentor entities completely (forces clean recreation on next restart)
      default: false
      selector:
        boolean:

retry_authentication:
  name: Retry Authentication
  description: Manually retry authentication when InfoMentor servers are unreliable
  fields:
    clear_cache:
      name: Clear Cache
      description: Whether to clear cached data and force fresh authentication
      default: false
      selector:
        boolean: